Repository Team-SWAcademy/SWAcademy-Android, pull requests merged in 2024-05, with the labels that each got.

#14 [UI/#12] 다회용기 세부사항 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/swacademy_android/presentation/MultiuseDetailActivity.kt
  app/src/main/res/drawable/ic_multiuse_detail_type_bowl.png
  app/src/main/res/drawable/ic_multiuse_detail_type_box.png
  app/src/main/res/drawable/ic_multiuse_detail_type_cup.png
  app/src/main/res/drawable/ic_multiuse_detail_type_cutlery.png
  app/src/main/res/drawable/img_multiuse_detail_represent_cup.png
  app/src/main/res/drawable/img_multiuse_detail_return_map.png
  app/src/main/res/drawable/img_multiuse_detail_store.png
  app/src/main/res/drawable/shape_d1e9ff_fill_e9f1ff_stroke_r50.xml
  app/src/main/res/drawable/shape_white_fill_d1e9ff_stroke_r20.xml
  app/src/main/res/layout/activity_multiuse_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 은정🐰, UI

#15 [Feat/#10] 홈화면 API 연결
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/swacademy_android/data/interceptor/AuthInterceptor.kt
  app/src/main/java/com/example/swacademy_android/data/model/response/HomeResponseDto.kt
  app/src/main/java/com/example/swacademy_android/data/repository/HomeRepositoryImpl.kt
  app/src/main/java/com/example/swacademy_android/data/service/HomeService.kt
  app/src/main/java/com/example/swacademy_android/di/NetworkModule.kt
  app/src/main/java/com/example/swacademy_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/swacademy_android/presentation/home/HomeViewModel.kt
  app/src/main/java/com/example/swacademy_android/presentation/home/RentalListAdapter.kt
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/drawable/img_sample_qr.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/item_current_rental_list.xml
  app/src/main/res/values/colors.xml
  local.properties
  settings.gradle.kts
Labels: FEAT, 서현🍀

#17 [UI/#12] 다회용기 세부사항 뷰 구현
  app/src/main/res/layout/activity_multiuse_detail.xml
Labels: 은정🐰, UI

#31 [Feat/#28] 마이페이지 API 연결
  app/src/main/java/com/example/swacademy_android/App.kt
  app/src/main/java/com/example/swacademy_android/data/datasource/MypageRemoteDataSource.kt
  app/src/main/java/com/example/swacademy_android/data/model/response/MypageResponseDto.kt
  app/src/main/java/com/example/swacademy_android/data/repository/MypageRepositoryImpl.kt
  app/src/main/java/com/example/swacademy_android/data/service/MypageService.kt
  app/src/main/java/com/example/swacademy_android/di/RepositoryModule.kt
  app/src/main/java/com/example/swacademy_android/di/ServiceModule.kt
  app/src/main/java/com/example/swacademy_android/domain/repository/MypageRepository.kt
  app/src/main/java/com/example/swacademy_android/presentation/MainActivity.kt
  app/src/main/java/com/example/swacademy_android/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/example/swacademy_android/presentation/mypage/MypageViewModel.kt
  app/src/main/res/drawable/ic_rental_color.png
  app/src/main/res/drawable/ic_return_color.png
  app/src/main/res/layout/activity_rental_info.xml
  app/src/main/res/layout/fragment_mypage.xml
Labels: FEAT, 서현🍀, UI

#33 [Feat/#32] 마이페이지 닉네임 수정 API 연결
  app/src/main/java/com/example/swacademy_android/data/datasource/MypageRemoteDataSource.kt
  app/src/main/java/com/example/swacademy_android/data/model/response/MypageEditNameResponseDto.kt
  app/src/main/java/com/example/swacademy_android/data/repository/MypageRepositoryImpl.kt
  app/src/main/java/com/example/swacademy_android/data/service/MypageService.kt
  app/src/main/java/com/example/swacademy_android/domain/repository/MypageRepository.kt
  app/src/main/java/com/example/swacademy_android/presentation/mypage/MypageFragment.kt
  app/src/main/java/com/example/swacademy_android/presentation/mypage/MypageViewModel.kt
Labels: FEAT, 서현🍀

#34 [Feat/#30] 포인트 현황 뷰 구현
  app/build.gradle
  app/src/main/java/com/example/swacademy_android/data/datasource/PointRemoteDataSource.kt
  app/src/main/java/com/example/swacademy_android/data/model/response/PointListResponseDto.kt
  app/src/main/java/com/example/swacademy_android/data/repository/PointRepositoryImpl.kt
  app/src/main/java/com/example/swacademy_android/data/service/PointService.kt
  app/src/main/java/com/example/swacademy_android/di/RepositoryModule.kt
  app/src/main/java/com/example/swacademy_android/di/ServiceModule.kt
  app/src/main/java/com/example/swacademy_android/presentation/MainActivity.kt
  app/src/main/java/com/example/swacademy_android/presentation/home/HomeFragment.kt
  app/src/main/java/com/example/swacademy_android/presentation/point/PointFragment.kt
  app/src/main/java/com/example/swacademy_android/presentation/point/PointListAdapter.kt
  app/src/main/java/com/example/swacademy_android/presentation/point/PointViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_point.xml
  app/src/main/res/layout/item_point.xml
  app/src/main/res/layout/item_point_load_more.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 서현🍀, UI
